CREATE DATABASE REGISTRO_ALUNOS_FARMERP;

USE REGISTRO_ALUNOS_FARMERP;

CREATE TABLE ALUNO (

	IDALUNO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR (100) NOT NULL,
	CPF CHAR(11) UNIQUE,
	DATANASCIMENTO (DATE) NOT NULL ,
	SEXO ENUM("M","F") NOT NULL,
	EMAIL VARCHAR(50) UNIQUE,
	SEMESTRE CHAR(1)

);


CREATE TABLE ESTAGIO (

	IDESTAGIO INT PRIMARY KEY AUTO_INCREMENT,
	ID_ALUNO INT UNIQUE,
	FOREIGN KEY (ID_ALUNO)
		REFERENCES ALUNO(IDALUNO),
	NOME VARCHAR (30) NOT NULL,
	PROFESSOR VARCHAR()

);

CREATE TABLE PROFESSOR (

	IDPROFESSOR INT PRIMARYKEY AUTO_INCREMENT,
	NOME VARCHAR (100),
	SEXO ENUM("M", "F"),
	ID_CURSO INT 

);

