CREATE DATABASE REGISTRO_ALUNOS_FAMERP;

USE REGISTRO_ALUNOS_FAMERP;

CREATE TABLE ALUNO (

	IDALUNO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR (100) NOT NULL,
	SEMESTRE CHAR(1) NOT NULL,
	RA CHAR(8) UNIQUE NOT NULL,
	EMAIL VARCHAR(50) UNIQUE NOT NULL

);


CREATE TABLE PROFESSOR (

	IDPROFESSOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR (100) NOT NULL,
	EMAIL VARCHAR(50) UNIQUE NOT NULL

);


CREATE TABLE ESTAGIO (

	IDESTAGIO INT PRIMARY KEY AUTO_INCREMENT,
	ID_ALUNO INT NOT NULL,
	FOREIGN KEY (ID_ALUNO)
		REFERENCES ALUNO(IDALUNO),
	ID_PROFESSOR INT NOT NULL,
	FOREIGN KEY (ID_PROFESSOR)
		REFERENCES PROFESSOR(IDPROFESSOR),
	NOME VARCHAR (30) NOT NULL,
	ANO CHAR(4) NOT NULL,
	LOCAL VARCHAR(60) NOT NULL

);


CREATE TABLE PROGRAMACAO (

	IDPROGRAMACAO INT PRIMARY KEY AUTO_INCREMENT,
	ID_ALUNO INT NOT NULL,
	FOREIGN KEY (ID_ALUNO)
		REFERENCES ALUNO(IDALUNO),
	ID_ESTAGIO INT UNIQUE NOT NULL,
	FOREIGN KEY (ID_ESTAGIO)
		REFERENCES ESTAGIO(IDESTAGIO),
	ID_PROFESSOR INT NOT NULL,
	FOREIGN KEY (ID_PROFESSOR)
		REFERENCES PROFESSOR(IDPROFESSOR),
	DATA DATE NOT NULL,
	HORA TIME NOT NULL

);


CREATE TABLE PRESENCA (

	IDPRESENCA INT PRIMARY KEY AUTO_INCREMENT,
	ID_PROGRAMACAO INT UNIQUE NOT NULL,
	FOREIGN KEY (ID_PROGRAMACAO)
		REFERENCES PROGRAMACAO(IDPROGRAMACAO),
	DATAPRESENCA TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);

CREATE TABLE USUARIOS (

	ID_USUARIOS INT PRIMARY KEY AUTO_INCREMENT,
	ID_RA CHAR UNIQUE NOT NULL,
	FOREIGN KEY (ID_RA)
		REFERENCES ALUNO(RA),
	ID_ALUNO INT UNIQUE NOT NULL,
	FOREIGN KEY (ID_ALUNO)
		REFERENCES ALUNO(IDALUNO),
	SENHA VARCHAR(255) NOT NULL

);